version: '3.8'
services:
  noip-duc:
    image: ghcr.nju.edu.cn/sqing33/noip-duc:latest
    container_name: noip-duc
    environment:
      - NOIP_USERNAME=
      - NOIP_PASSWORD=
      - NOIP_HOSTNAMES=all.ddnskey.com
